export const catalogConstants = {
    VIEW: 'VIEW_BTN',
    ADD: 'ADD_TO_CART',
    UPDATE_SUIT: 'UPDATE_BODYSUIT_DISPLAY',
    UPDATE_MASK: 'UPDATE_MASK_DISPLAY',
    UPDATE_GLOVES: 'UPDATE_GLOVES_DISPLAY'
};