export const userConstants = {
    SIGNIN_REQUEST: 'USERS_SIGNIN_REQUEST',
    SIGNIN_SUCCESS: 'USERS_SIGNIN_SUCCESS',
    SIGNIN_FAILURE: 'USERS_SIGNIN_FAILURE',

    SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'USERS_SIGNUP_FAILURE',

    UPDATE_REQUEST: 'USERS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'USERS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'USERS_UPDATE_FAILURE',
    
    LOGOUT: 'USERS_LOGOUT',
};
